# Generated by Django 5.1.2 on 2024-12-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAF', '0003_alter_agendamentodisponivel_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviço',
            name='nome',
            field=models.CharField(choices=[('Declaração IR pessoa física', 'Declaração IR pessoa física'), ('MEI', 'Obrigações fiscais do Microempreendedor Individual (MEI)'), ('CNPJ', 'Cadastro Nacional de Pessoas Jurídicas (CNPJ)'), ('CAEPF', 'Cadastro de Atividades Econômicas das Pessoas Físicas (CAEPF)'), ('Certidão negativa', 'Certidão negativa'), ('ITR', 'Serviços relativos ao ITR'), ('CNIR', 'Cadastro Nacional de Imóveis Rurais (CNIR)'), ('Parcelamentos de dívidas tributárias', 'Parcelamentos de dívidas tributárias'), ('Geração de documentos para pagamento de impostos', 'Geração de documentos para pagamento de impostos'), ('Apoio em serviços do e-Social Doméstico', 'Apoio em serviços do e-Social Doméstico'), ('Consultas de dívidas e pendências fiscais', 'Consultas de dívidas e pendências fiscais'), ('Malha e Restituição do IR', 'Malha e Restituição do IR')], max_length=60),
        ),
    ]
