# Generated by Django 5.2.6 on 2025-09-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NAF', '0008_agendamento_finalizado_alter_feedback_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='AgendamentoDisponivel',
            new_name='agendamento_disponivel',
        ),
    ]
